### PR TITLE
ganjine@mohammad-sn: new desklet that shows random Persian poems

### PR DESCRIPTION
**Pull request by mohammad-sn**
This desklet shows random Persian poems on the desktop from [Ganjoor](https://ganjoor.net/), a Persian poetry web site

### CODE REVIEW

**Comment by jaszhix** [comment]
Hi mohammad-sn, I wasn't able to get this working on Cinnamon 3.4. I got a stack trace:

```sh
info t=2017-06-14T01:26:56.811Z Installing settings for ganjine@mohammad-sn
info t=2017-06-14T01:26:56.812Z Settings successfully installed for ganjine@mohammad-sn
error t=2017-06-14T01:26:56.818Z fontprep.join(...).replaceAll is not a function
trace t=2017-06-14T01:26:56.818Z 
<----------------
MyDesklet.prototype._onSettingsChanged@/home/jason/.local/share/cinnamon/desklets/ganjine@mohammad-sn/desklet.js:163:24
MyDesklet.prototype._init@/home/jason/.local/share/cinnamon/desklets/ganjine@mohammad-sn/desklet.js:141:9
MyDesklet@/home/jason/.local/share/cinnamon/desklets/ganjine@mohammad-sn/desklet.js:32:5
main@/home/jason/.local/share/cinnamon/desklets/ganjine@mohammad-sn/desklet.js:355:19
_createDesklets@/usr/share/cinnamon/js/ui/deskletManager.js:290:19
_loadDesklet@/usr/share/cinnamon/js/ui/deskletManager.js:251:23
finishExtensionLoad@/usr/share/cinnamon/js/ui/deskletManager.js:153:18
loadExtension@/usr/share/cinnamon/js/ui/extension.js:451:17
_onEnabledDeskletsChanged@/usr/share/cinnamon/js/ui/deskletManager.js:203:16
---------------->
error t=2017-06-14T01:26:56.818Z [Desklet "ganjine@mohammad-sn"]: Failed to evaluate 'main' function on desklet: ganjine@mohammad-sn/0
error t=2017-06-14T01:26:56.819Z Could not load desklet ganjine@mohammad-sn

```
Replacing

```js
let fontname = fontprep.join(' ').replaceAll(',', ' ');
```

with

```js
let fontname = fontprep.join(' ').replace(/,/, ' ');
```
fixes it for me.

**Comment by mohammad-sn** [comment]
Hi @jaszhix, thank you so much for your feedback, I'll look into it to fix the issue.

**Comment by mohammad-sn** [comment]
I fixed the issue, it must work now.

**Comment by jaszhix** [comment]
Is the font included needed for the applet to display correctly? I was able to get it working without installing it. I don't recommend including binary files with your applet since its not easy to see what its contents are. There are typically plenty of fonts included in most distros. Another worry is [fonts being used as exploits](http://news.softpedia.com/news/vulnerability-in-font-processing-library-affects-linux-openoffice-firefox-500027.shtml). Not that you would do this, but its one less thing to worry about.

**Comment by mohammad-sn** [comment]
It's an artistic font used in most Iranian poetry books. You are right, I think I can remove it and instruct users to install it themselves if they want to.
